"""
Import career decision tree nodes into the database.
Populates the career_nodes table with career progression,
trading, startup, and freelancing paths.

Usage: python3 import_career_nodes.py
"""

import sqlite3
import json
from pathlib import Path

DB_PATH = Path(__file__).parent / "career_tree.db"

# ═══════════════════════════════════════════════════════════════
# All career tree nodes (excluding root, which stays in frontend)
# ═══════════════════════════════════════════════════════════════

CAREER_NODES = [
    # ─── CAREER PATH: Phase 0 (Yr 0–2) ───
    {
        "id": "p1_promoted",
        "phase": 0,
        "node_type": "career",
        "label": "✦ Promoted to L4\\nat Motive",
        "salary": "400–475K PKR/mo\\n+RSU uplift",
        "probability": 0.52,
        "color": "#00e5ff",
        "note": "~50–55% chance if strong performer. RSU allocation jumps ~3x. IPO equity becomes meaningful.",
        "children": ["p2_l4_staymotive", "p2_l4_remoteUSD", "p2_l4_switchlocal"],
    },
    {
        "id": "p1_notpromoted_stay",
        "phase": 0,
        "node_type": "career",
        "label": "✗ Not Promoted\\nStay at Motive",
        "salary": "255–270K PKR/mo\\n(increments only)",
        "probability": 0.28,
        "color": "#ff9f43",
        "note": "Annual 10–15% increments. Risk of getting stuck. Good time to switch teams internally (ML Platform, CV) to reset promo clock.",
        "children": ["p2_np_teamswitch", "p2_np_motive_retry", "p2_np_remote"],
    },
    {
        "id": "p1_switch_local",
        "phase": 0,
        "node_type": "career",
        "label": "↗ Leave Motive\\nJoin Securiti /\\n10Pearls / Arbisoft",
        "salary": "320–420K PKR/mo",
        "probability": 0.20,
        "color": "#a29bfe",
        "note": "30–50% salary jump immediately. Lose Motive RSU vesting & IPO upside. Good option if promotion seems blocked.",
        "children": ["p2_local_promoted", "p2_local_stagnate", "p2_local_remote"],
    },
    # ─── CAREER PATH: Phase 1 (Yr 2–4) — From Promoted ───
    {
        "id": "p2_l4_staymotive",
        "phase": 1,
        "node_type": "career",
        "label": "Stay Motive\\nTarget L5",
        "salary": "450–520K PKR/mo\\n(increments)",
        "probability": 0.40,
        "color": "#00e5ff",
        "note": "L4→L5 takes 2–4 years. If IPO happens here, RSU windfall possible. Stable but slower than remote.",
        "children": ["p3_l5_achieved", "p3_l5_stalled_motive"],
    },
    {
        "id": "p2_l4_remoteUSD",
        "phase": 1,
        "node_type": "career",
        "label": "🌐 Go Remote\\nTuring / Toptal /\\nDirect US Startup",
        "salary": "900K–1.85M PKR/mo\\n($40–80K USD)",
        "probability": 0.38,
        "color": "#00ff9f",
        "note": "5–8x salary jump. Motive L4 title + AI specialization = strong remote profile. 55–65% chance of landing within 6 months.",
        "children": ["p3_remote_senior", "p3_remote_plateau"],
    },
    {
        "id": "p2_l4_switchlocal",
        "phase": 1,
        "node_type": "career",
        "label": "↗ Switch Local\\nSecuriti / MNC\\nas L4/Senior",
        "salary": "500–700K PKR/mo",
        "probability": 0.22,
        "color": "#fd79a8",
        "note": "Motive L4 credential opens Senior doors at Tier-1 local companies. Less upside than remote but stable.",
        "children": ["p3_local_senior_rise", "p3_local_switch_remote"],
    },
    # ─── CAREER PATH: Phase 1 (Yr 2–4) — From Not Promoted ───
    {
        "id": "p2_np_teamswitch",
        "phase": 1,
        "node_type": "career",
        "label": "Switch Team\\nML Platform / CV\\n(internal)",
        "salary": "270–300K PKR/mo\\n+ reset promo clock",
        "probability": 0.38,
        "color": "#fdcb6e",
        "note": "Lateral move to ML Platform or CV team. Resets promotion narrative. 55–65% chance of L4 within 18 months from new team.",
        "children": ["p3_teamswitch_l4", "p3_teamswitch_stuck"],
    },
    {
        "id": "p2_np_motive_retry",
        "phase": 1,
        "node_type": "career",
        "label": "Stay Same Team\\nRetry Promotion",
        "salary": "260–285K PKR/mo",
        "probability": 0.32,
        "color": "#e17055",
        "note": "Risky path. Same team, same manager. Promotion retry has 35–45% chance. If fails again, strong signal to leave.",
        "children": ["p3_retry_promoted", "p3_retry_failed_leave"],
    },
    {
        "id": "p2_np_remote",
        "phase": 1,
        "node_type": "career",
        "label": "🌐 Skip Local,\\nGo Remote\\nDespite L3",
        "salary": "600–950K PKR/mo\\n($27–43K USD)",
        "probability": 0.30,
        "color": "#55efc4",
        "note": "Harder without L4 but doable on platforms like Turing with portfolio. 35–45% success rate. Lower USD band than L4 route.",
        "children": ["p3_remote_l3_grows", "p3_remote_l3_contract"],
    },
    # ─── CAREER PATH: Phase 1 (Yr 2–4) — From Switch Local ───
    {
        "id": "p2_local_promoted",
        "phase": 1,
        "node_type": "career",
        "label": "Promoted\\nSenior AI Eng\\nat New Company",
        "salary": "500–650K PKR/mo",
        "probability": 0.48,
        "color": "#a29bfe",
        "note": "Senior title at Tier-1 local company. Good CV credential for remote applications. 2 years typical.",
        "children": ["p3_local_stay_staff", "p3_local_pivot_remote"],
    },
    {
        "id": "p2_local_stagnate",
        "phase": 1,
        "node_type": "career",
        "label": "Stagnate\\nNo Promo\\n(same level)",
        "salary": "350–400K PKR/mo\\n(increments)",
        "probability": 0.27,
        "color": "#636e72",
        "note": "Common at mid-size companies. If stagnating at year 3, the only move is remote or another company hop.",
        "children": ["p3_stagnate_remote", "p3_stagnate_hop"],
    },
    {
        "id": "p2_local_remote",
        "phase": 1,
        "node_type": "career",
        "label": "🌐 Go Remote\\nfrom New Company",
        "salary": "700–1.2M PKR/mo\\n($32–55K USD)",
        "probability": 0.25,
        "color": "#00cec9",
        "note": "Using new company's Senior title to jump to remote. Effective strategy. 50–60% landing rate.",
        "children": ["p3_remote_mid_climb", "p3_remote_mid_stable"],
    },
    # ─── CAREER PATH: Phase 2 (Yr 4–7) ───
    {
        "id": "p3_l5_achieved",
        "phase": 2,
        "node_type": "career",
        "label": "✦ L5 Senior\\nat Motive",
        "salary": "800–900K PKR/mo\\n+ RSU",
        "probability": 0.35,
        "color": "#00e5ff",
        "note": "Strong performer track. IPO RSU could add $10–30K one-time. Local ceiling approaching.",
        "children": ["p4_motive_staff", "p4_l5_goremote"],
    },
    {
        "id": "p3_l5_stalled_motive",
        "phase": 2,
        "node_type": "career",
        "label": "Stalled at L4\\nMotive (no L5)",
        "salary": "520–600K PKR/mo",
        "probability": 0.65,
        "color": "#fab1a0",
        "note": "Majority of L4 engineers don't reach L5 within 4 years. This is the most common path. Time to go remote.",
        "children": ["p4_l4stall_remote", "p4_l4stall_local_sr"],
    },
    {
        "id": "p3_remote_senior",
        "phase": 2,
        "node_type": "career",
        "label": "📈 Senior ML Eng\\nRemote (Direct\\nEmployment)",
        "salary": "1.6–2.5M PKR/mo\\n($70–110K USD)",
        "probability": 0.55,
        "color": "#00ff9f",
        "note": "Moved from platform (Turing) to direct employment. Full benefits, equity, stable. Best risk-adjusted remote path.",
        "children": ["p4_remote_staff", "p4_remote_stable_senior"],
    },
    {
        "id": "p3_remote_plateau",
        "phase": 2,
        "node_type": "career",
        "label": "Plateau on\\nRemote Platform\\n(contract gaps)",
        "salary": "800–1.1M PKR/mo",
        "probability": 0.45,
        "color": "#fdcb6e",
        "note": "Platform contract gaps or rate stagnation. Common with Turing/Toptal. Solution: build direct client relationships or switch platforms.",
        "children": ["p4_platform_pivot", "p4_platform_direct"],
    },
    {
        "id": "p3_local_senior_rise",
        "phase": 2,
        "node_type": "career",
        "label": "Senior → Staff\\nLocal Company",
        "salary": "700–900K PKR/mo",
        "probability": 0.35,
        "color": "#fd79a8",
        "note": "Top-tier local comp. Still 2–3x below remote but strong PKR purchasing power. Good if lifestyle suits local.",
        "children": ["p4_local_staff", "p4_local_sr_remote"],
    },
    {
        "id": "p3_local_switch_remote",
        "phase": 2,
        "node_type": "career",
        "label": "🌐 Senior title\\n→ Go Remote",
        "salary": "1.4–2.2M PKR/mo\\n($60–100K)",
        "probability": 0.65,
        "color": "#00cec9",
        "note": "Using local Senior title to land remote role. Highly effective — Senior at Securiti/Motive is strong signal.",
        "children": ["p4_remote_sr_direct", "p4_remote_sr_stable"],
    },
    {
        "id": "p3_teamswitch_l4",
        "phase": 2,
        "node_type": "career",
        "label": "✦ Got L4 after\\nTeam Switch",
        "salary": "380–475K PKR/mo",
        "probability": 0.58,
        "color": "#fdcb6e",
        "note": "Team switch paid off. Now at L4 by year 4. Slightly behind original promoted path but back on track.",
        "children": ["p4_l4late_remote", "p4_l4late_motive"],
    },
    {
        "id": "p3_teamswitch_stuck",
        "phase": 2,
        "node_type": "career",
        "label": "Still L3/low L4\\nafter team switch",
        "salary": "290–340K PKR/mo",
        "probability": 0.42,
        "color": "#b2bec3",
        "note": "By year 4, if still not at solid L4, Motive is no longer the right vehicle. Remote or local hop is urgent.",
        "children": ["p4_stuck_emergency_remote", "p4_stuck_local_hop"],
    },
    {
        "id": "p3_retry_promoted",
        "phase": 2,
        "node_type": "career",
        "label": "✦ Retry Worked\\nL4 at Motive\\n(yr 3–4)",
        "salary": "400–475K PKR/mo",
        "probability": 0.38,
        "color": "#e17055",
        "note": "Late L4. Lost 1–1.5 years vs. original track. Consider fast-tracking remote from here.",
        "children": ["p4_l4late_remote", "p4_l4late_motive"],
    },
    {
        "id": "p3_retry_failed_leave",
        "phase": 2,
        "node_type": "career",
        "label": "Failed Again\\n→ Leave Motive",
        "salary": "350–500K PKR/mo\\n(external)",
        "probability": 0.62,
        "color": "#d63031",
        "note": "Clear signal: Motive wasn't the right fit or wrong manager. External jump with 2+ years AI exp yields 40–60% raise.",
        "children": ["p4_exited_motive_remote", "p4_exited_motive_local"],
    },
    {
        "id": "p3_remote_l3_grows",
        "phase": 2,
        "node_type": "career",
        "label": "Remote Grows\\nMid-level ML\\n($35–55K)",
        "salary": "800K–1.3M PKR/mo",
        "probability": 0.48,
        "color": "#55efc4",
        "note": "Proved value remotely without L4 title. Rate negotiations possible after 12–18 months of strong delivery.",
        "children": ["p4_remote_mid_senior", "p4_remote_mid_stable2"],
    },
    {
        "id": "p3_remote_l3_contract",
        "phase": 2,
        "node_type": "career",
        "label": "Contract Gaps /\\nLower Rates\\n($25–35K)",
        "salary": "580K–810K PKR/mo",
        "probability": 0.52,
        "color": "#636e72",
        "note": "L3 without portfolio struggles on premium platforms. Better to return to local job for 6–12 months and rebuild.",
        "children": ["p4_contract_rebuild", "p4_contract_grind"],
    },
    {
        "id": "p3_local_stay_staff",
        "phase": 2,
        "node_type": "career",
        "label": "Promoted to\\nStaff/Lead at\\nLocal Company",
        "salary": "750–950K PKR/mo",
        "probability": 0.40,
        "color": "#a29bfe",
        "note": "Senior/Staff at Tier-1 local. High PKR comp, leadership experience, but remote gap growing.",
        "children": ["p4_local_staff", "p4_local_sr_remote"],
    },
    {
        "id": "p3_local_pivot_remote",
        "phase": 2,
        "node_type": "career",
        "label": "🌐 Pivot Remote\\nfrom Local Senior",
        "salary": "1.3–2.0M PKR/mo\\n($55–90K)",
        "probability": 0.60,
        "color": "#00cec9",
        "note": "Senior AI title at reputable local company is strong remote signal. 55–65% chance of landing.",
        "children": ["p4_remote_sr_direct", "p4_remote_sr_stable"],
    },
    {
        "id": "p3_stagnate_remote",
        "phase": 2,
        "node_type": "career",
        "label": "🌐 Escape\\nStagnation via\\nRemote",
        "salary": "700K–1.4M PKR/mo",
        "probability": 0.55,
        "color": "#00cec9",
        "note": "Pivoting remote from a stagnating local role. Portfolio quality and AI specialization are key differentiators.",
        "children": ["p4_platform_pivot", "p4_remote_stable_senior"],
    },
    {
        "id": "p3_stagnate_hop",
        "phase": 2,
        "node_type": "career",
        "label": "Company Hop\\nto Better Local",
        "salary": "450–600K PKR/mo",
        "probability": 0.45,
        "color": "#b2bec3",
        "note": "Another local hop. Incrementally better but ceiling remains. Remote is still the long-term path.",
        "children": ["p4_local_staff", "p4_local_sr_remote"],
    },
    {
        "id": "p3_remote_mid_climb",
        "phase": 2,
        "node_type": "career",
        "label": "Remote Growth\\nSenior ML\\n($55–85K)",
        "salary": "1.3–2.0M PKR/mo",
        "probability": 0.52,
        "color": "#00cec9",
        "note": "Steady remote career growth. Building direct employer relationships. High trajectory.",
        "children": ["p4_remote_staff", "p4_remote_stable_senior"],
    },
    {
        "id": "p3_remote_mid_stable",
        "phase": 2,
        "node_type": "career",
        "label": "Stable Remote\\nMid-level\\n($40–55K)",
        "salary": "925K–1.3M PKR/mo",
        "probability": 0.48,
        "color": "#74b9ff",
        "note": "Good income but plateaued. Need specialization uplift (LLM/GenAI) to break to senior tier.",
        "children": ["p4_platform_pivot", "p4_platform_direct"],
    },
    # ─── CAREER PATH: Phase 3 (Yr 7–10) — Final outcomes ───
    {
        "id": "p4_motive_staff",
        "phase": 3,
        "node_type": "career",
        "label": "🏆 Staff Eng\\nat Motive",
        "salary": "1.2–1.5M PKR/mo\\n~$55–65K/yr",
        "probability": 0.18,
        "color": "#00e5ff",
        "note": "Best local outcome. Rare — fewer than 5 Staff engineers in Motive Pakistan. IPO windfall could be $50–150K if timing is right.",
        "children": [],
    },
    {
        "id": "p4_l5_goremote",
        "phase": 3,
        "node_type": "career",
        "label": "🌐 L5 Cred\\n→ Remote Staff\\n($100–150K)",
        "salary": "2.3–3.5M PKR/mo",
        "probability": 0.82,
        "color": "#00ff9f",
        "note": "Motive L5 + 7 years AI exp is extremely competitive remotely. Near-guaranteed $100K+ role. This is the jackpot path.",
        "children": [],
    },
    {
        "id": "p4_l4stall_remote",
        "phase": 3,
        "node_type": "career",
        "label": "🌐 L4 Stall\\n→ Remote Senior\\n($70–100K)",
        "salary": "1.6–2.3M PKR/mo",
        "probability": 0.60,
        "color": "#55efc4",
        "note": "Stalled L4 uses Motive brand to go remote. Still excellent outcome. 5–8 years local AI exp is strong.",
        "children": [],
    },
    {
        "id": "p4_l4stall_local_sr",
        "phase": 3,
        "node_type": "career",
        "label": "Switch Local\\nSenior at\\nSecuriti / MNC",
        "salary": "700–950K PKR/mo",
        "probability": 0.40,
        "color": "#fdcb6e",
        "note": "Using L4 Motive to get Senior elsewhere. Good PKR income but remote gap widens. Consider remote by year 10.",
        "children": [],
    },
    {
        "id": "p4_remote_staff",
        "phase": 3,
        "node_type": "career",
        "label": "🏆 Remote Staff\\nML Engineer\\n($120–180K)",
        "salary": "2.8–4.2M PKR/mo",
        "probability": 0.30,
        "color": "#00ff9f",
        "note": "Best remote outcome. Direct employment at US/EU scale-up. Full benefits, equity, stock options.",
        "children": [],
    },
    {
        "id": "p4_remote_stable_senior",
        "phase": 3,
        "node_type": "career",
        "label": "Remote Senior\\nML (stable)\\n($80–110K)",
        "salary": "1.85–2.5M PKR/mo",
        "probability": 0.70,
        "color": "#74b9ff",
        "note": "Solid, stable senior remote role. Excellent PKR purchasing power. This outcome alone beats every local path.",
        "children": [],
    },
    {
        "id": "p4_platform_pivot",
        "phase": 3,
        "node_type": "career",
        "label": "Platform→Direct\\nRemote Upgrade\\n($70–95K)",
        "salary": "1.6–2.2M PKR/mo",
        "probability": 0.50,
        "color": "#81ecec",
        "note": "Moved from Turing/Toptal to direct employment. Stability improves dramatically. Good long-term position.",
        "children": [],
    },
    {
        "id": "p4_platform_direct",
        "phase": 3,
        "node_type": "career",
        "label": "Still on\\nPlatforms\\n($50–70K)",
        "salary": "1.16–1.6M PKR/mo",
        "probability": 0.50,
        "color": "#b2bec3",
        "note": "Contract-based remote. Decent income but variable. Consider direct outreach to convert to employment.",
        "children": [],
    },
    {
        "id": "p4_local_staff",
        "phase": 3,
        "node_type": "career",
        "label": "Staff/Principal\\nLocal (Tier-1)",
        "salary": "1.0–1.4M PKR/mo",
        "probability": 0.25,
        "color": "#a29bfe",
        "note": "Top of local ladder. Securiti/10Pearls Staff level. Strong local prestige and comp. Remote option always open.",
        "children": [],
    },
    {
        "id": "p4_local_sr_remote",
        "phase": 3,
        "node_type": "career",
        "label": "🌐 Local Sr\\n→ Late Remote\\n($70–100K)",
        "salary": "1.6–2.3M PKR/mo",
        "probability": 0.75,
        "color": "#00cec9",
        "note": "Going remote at year 7–10 with 8+ years local AI exp. Always achievable. The remote window never closes for AI engineers.",
        "children": [],
    },
    {
        "id": "p4_l4late_remote",
        "phase": 3,
        "node_type": "career",
        "label": "🌐 Late L4\\n→ Remote Mid\\n($55–80K)",
        "salary": "1.3–1.85M PKR/mo",
        "probability": 0.58,
        "color": "#55efc4",
        "note": "Delayed but still solid remote landing. 6+ years AI exp compensates for slower internal track.",
        "children": [],
    },
    {
        "id": "p4_l4late_motive",
        "phase": 3,
        "node_type": "career",
        "label": "Stay Motive\\nTarget L5\\n(Yr 7–10)",
        "salary": "700–900K PKR/mo",
        "probability": 0.42,
        "color": "#fab1a0",
        "note": "Late L5 attempt. Possible but the comp gap vs remote has widened to 3–4x. Hard to justify staying.",
        "children": [],
    },
    {
        "id": "p4_stuck_emergency_remote",
        "phase": 3,
        "node_type": "career",
        "label": "Emergency\\nRemote Pivot\\n($40–65K)",
        "salary": "925K–1.5M PKR/mo",
        "probability": 0.45,
        "color": "#fdcb6e",
        "note": "Even from a stalled position, 4+ years AI exp is enough for remote. Lower band but still 4–6x current.",
        "children": [],
    },
    {
        "id": "p4_stuck_local_hop",
        "phase": 3,
        "node_type": "career",
        "label": "Local Company\\nHop (Again)",
        "salary": "400–550K PKR/mo",
        "probability": 0.55,
        "color": "#636e72",
        "note": "Multiple hops without leveling up. Diminishing returns. Strong signal to invest in remote skills.",
        "children": [],
    },
    {
        "id": "p4_exited_motive_remote",
        "phase": 3,
        "node_type": "career",
        "label": "🌐 Post-Motive\\nRemote ($55–85K)",
        "salary": "1.3–2.0M PKR/mo",
        "probability": 0.52,
        "color": "#00cec9",
        "note": "'Failed' at Motive but 4+ years AI exp at a well-known company is still great remote profile.",
        "children": [],
    },
    {
        "id": "p4_exited_motive_local",
        "phase": 3,
        "node_type": "career",
        "label": "Senior Local\\n(Post-Motive\\ncompany)",
        "salary": "500–700K PKR/mo",
        "probability": 0.48,
        "color": "#b2bec3",
        "note": "Motive experience opens doors at Tier-2 companies as Senior. Solid PKR income.",
        "children": [],
    },
    {
        "id": "p4_remote_sr_direct",
        "phase": 3,
        "node_type": "career",
        "label": "🏆 Remote Staff\\nor Sr Direct\\n($100–140K)",
        "salary": "2.3–3.2M PKR/mo",
        "probability": 0.35,
        "color": "#00ff9f",
        "note": "Direct employment at US/EU company at Staff/Senior level. Equity, benefits, growth. Excellent outcome.",
        "children": [],
    },
    {
        "id": "p4_remote_sr_stable",
        "phase": 3,
        "node_type": "career",
        "label": "Remote Senior\\nStable ($75–100K)",
        "salary": "1.7–2.3M PKR/mo",
        "probability": 0.65,
        "color": "#74b9ff",
        "note": "Stable senior remote role. Great PKR income. Lower stress than staff-track. Excellent lifestyle balance.",
        "children": [],
    },
    {
        "id": "p4_remote_mid_senior",
        "phase": 3,
        "node_type": "career",
        "label": "Remote Senior\\n(grew from L3)\\n($70–95K)",
        "salary": "1.6–2.2M PKR/mo",
        "probability": 0.50,
        "color": "#81ecec",
        "note": "Proved remote value from L3. Grown to senior. Shows hustle and execution — valued traits remotely.",
        "children": [],
    },
    {
        "id": "p4_remote_mid_stable2",
        "phase": 3,
        "node_type": "career",
        "label": "Mid Remote\\nPlateau ($45–65K)",
        "salary": "1.04–1.5M PKR/mo",
        "probability": 0.50,
        "color": "#b2bec3",
        "note": "Stable but lower remote income. LLM/GenAI specialization would break through to senior tier.",
        "children": [],
    },
    {
        "id": "p4_contract_rebuild",
        "phase": 3,
        "node_type": "career",
        "label": "Rebuilt → Better\\nRemote ($55–80K)",
        "salary": "1.3–1.85M PKR/mo",
        "probability": 0.45,
        "color": "#fdcb6e",
        "note": "Took step back locally for 6–12 months, rebuilt portfolio, relaunched remote at higher rate.",
        "children": [],
    },
    {
        "id": "p4_contract_grind",
        "phase": 3,
        "node_type": "career",
        "label": "Low Remote\\nGrind ($30–45K)",
        "salary": "695K–1.04M PKR/mo",
        "probability": 0.55,
        "color": "#636e72",
        "note": "Survived on contract work but not thriving. Still 3–4x current salary but far below potential.",
        "children": [],
    },
    # ═══════════════════════════════════════════════════════════
    # TRADING PATH
    # ═══════════════════════════════════════════════════════════
    # ─── Phase 0: Start Trading ───
    {
        "id": "p1_trading",
        "phase": 0,
        "node_type": "trading",
        "label": "📈 Start Trading\\n(Side Hustle)",
        "salary": "220K PKR/mo\\n+ trading P&L",
        "probability": 0.15,
        "color": "#f39c12",
        "note": "Keep job, learn and trade evenings/weekends. Start with small capital ($500–2K). 6–12 months learning curve before any consistency.",
        "children": ["p2_trade_crypto", "p2_trade_algo", "p2_trade_stocks"],
    },
    # ─── Phase 1: Trading Specializations ───
    {
        "id": "p2_trade_crypto",
        "phase": 1,
        "node_type": "trading",
        "label": "₿ Crypto / Forex\\nActive Trading",
        "salary": "220K + 50–150K\\nPKR/mo (variable)",
        "probability": 0.35,
        "color": "#f39c12",
        "note": "High volatility = high risk. 24/7 markets. Most retail traders lose money in first 2 years. Leverage is dangerous. Need strict risk management.",
        "children": ["p3_trade_profitable", "p3_trade_breakeven", "p3_trade_loss"],
    },
    {
        "id": "p2_trade_algo",
        "phase": 1,
        "node_type": "trading",
        "label": "🤖 Algo / Quant\\nTrading Bots",
        "salary": "220K + 100–300K\\nPKR/mo (if working)",
        "probability": 0.30,
        "color": "#f39c12",
        "note": "Leverage AI/ML skills to build automated strategies. Backtesting is easy, live trading is hard. Edge decays. Infrastructure costs. Best synergy with your skillset.",
        "children": ["p3_trade_algo_edge", "p3_trade_breakeven", "p3_trade_loss"],
    },
    {
        "id": "p2_trade_stocks",
        "phase": 1,
        "node_type": "trading",
        "label": "📊 Stocks &\\nOptions Trading",
        "salary": "220K + 30–100K\\nPKR/mo (variable)",
        "probability": 0.35,
        "color": "#f39c12",
        "note": "Swing trading, options strategies (covered calls, spreads). Lower volatility than crypto. Requires $5–20K capital for meaningful returns. Tax implications vary.",
        "children": ["p3_trade_profitable", "p3_trade_breakeven", "p3_trade_loss"],
    },
    # ─── Phase 2: Trading Outcomes ───
    {
        "id": "p3_trade_profitable",
        "phase": 2,
        "node_type": "trading",
        "label": "💰 Consistently\\nProfitable\\n(scale up)",
        "salary": "500K–1.5M PKR/mo\\n(job + trading)",
        "probability": 0.25,
        "color": "#f39c12",
        "note": "Top 10–15% of traders. Consistent monthly returns of 5–15%. Can scale with more capital. Key: risk management and emotional discipline.",
        "children": ["p4_trade_fulltime", "p4_trade_sideincome"],
    },
    {
        "id": "p3_trade_algo_edge",
        "phase": 2,
        "node_type": "trading",
        "label": "🤖 Found Edge\\nAutomated Returns",
        "salary": "800K–2M PKR/mo\\n(job + algo profits)",
        "probability": 0.20,
        "color": "#f39c12",
        "note": "Rare but powerful. ML-based edge in market microstructure, sentiment, or arbitrage. Edge decays — constant iteration needed. Could lead to quant fund role.",
        "children": ["p4_trade_fulltime", "p4_trade_quant_fund"],
    },
    {
        "id": "p3_trade_breakeven",
        "phase": 2,
        "node_type": "trading",
        "label": "😐 Breakeven /\\nSmall Gains\\n(hobby level)",
        "salary": "220–300K PKR/mo\\n(job income only)",
        "probability": 0.45,
        "color": "#b2bec3",
        "note": "Most common outcome. Not losing but not making real money. Trading becomes a hobby/learning experience. Time may be better spent on career or startup.",
        "children": ["p4_trade_sideincome", "p4_trade_quit"],
    },
    {
        "id": "p3_trade_loss",
        "phase": 2,
        "node_type": "trading",
        "label": "📉 Net Losses\\nCapital Blown",
        "salary": "220K PKR/mo\\n(back to job only)",
        "probability": 0.30,
        "color": "#d63031",
        "note": "60–80% of retail traders lose money. Especially common with leverage, crypto, and no risk management. Expensive lesson but recoverable if you kept your job.",
        "children": ["p4_trade_quit", "p4_trade_restart"],
    },
    # ─── Phase 3: Trading Final Outcomes ───
    {
        "id": "p4_trade_fulltime",
        "phase": 3,
        "node_type": "trading",
        "label": "🏆 Full-Time\\nTrader / Fund",
        "salary": "1.5–5M+ PKR/mo\\n($7–22K+/mo)",
        "probability": 0.15,
        "color": "#f39c12",
        "note": "Quit job, trade full-time or start small fund. Extremely rare outcome. Need 2+ years of consistent track record and $50K+ capital. High stress, no safety net.",
        "children": [],
    },
    {
        "id": "p4_trade_quant_fund",
        "phase": 3,
        "node_type": "trading",
        "label": "🏦 Join Quant\\nFund / Prop Shop",
        "salary": "2–4M PKR/mo\\n($85–175K/yr)",
        "probability": 0.10,
        "color": "#f39c12",
        "note": "Algo trading track record + AI/ML skills = strong profile for prop trading firms. Jane Street, Two Sigma, or remote quant roles. Very competitive.",
        "children": [],
    },
    {
        "id": "p4_trade_sideincome",
        "phase": 3,
        "node_type": "trading",
        "label": "📊 Trading as\\nSide Income",
        "salary": "Career salary +\\n200–500K PKR/mo",
        "probability": 0.55,
        "color": "#74b9ff",
        "note": "Best risk-adjusted outcome. Keep career for stability, trade for supplemental income. 2–5 hours/week once systems are in place.",
        "children": [],
    },
    {
        "id": "p4_trade_quit",
        "phase": 3,
        "node_type": "trading",
        "label": "🚪 Quit Trading\\nBack to Career",
        "salary": "Career salary only",
        "probability": 0.30,
        "color": "#636e72",
        "note": "Lost capital or time. Not a failure — learned risk management, markets, and discipline. These skills transfer to investing and financial planning.",
        "children": [],
    },
    {
        "id": "p4_trade_restart",
        "phase": 3,
        "node_type": "trading",
        "label": "🔄 Restart with\\nBetter Strategy",
        "salary": "220K PKR/mo\\n+ small trades",
        "probability": 0.40,
        "color": "#fdcb6e",
        "note": "Lost money but learned lessons. Restart with smaller position sizes, better risk management. Many successful traders blew up their first account.",
        "children": [],
    },
    # ═══════════════════════════════════════════════════════════
    # STARTUP PATH
    # ═══════════════════════════════════════════════════════════
    # ─── Phase 0: Start Building ───
    {
        "id": "p1_startup",
        "phase": 0,
        "node_type": "startup",
        "label": "🚀 Build Products\\n(Side Hustle)",
        "salary": "220K PKR/mo\\n+ $0 MRR",
        "probability": 0.12,
        "color": "#e84393",
        "note": "Start building MVP nights/weekends. Ship fast, validate with real users. Most important: pick a problem you understand deeply. AI/ML expertise is your moat.",
        "children": ["p2_startup_ai_saas", "p2_startup_devtools", "p2_startup_general"],
    },
    # ─── Phase 1: Startup Specializations ───
    {
        "id": "p2_startup_ai_saas",
        "phase": 1,
        "node_type": "startup",
        "label": "🤖 AI/ML SaaS\\nProduct",
        "salary": "220K + 0–50K\\nPKR/mo",
        "probability": 0.40,
        "color": "#e84393",
        "note": "Leverage your AI expertise. B2B AI tools (document processing, computer vision APIs, ML pipelines). Crowded market but your technical depth is real. Ship an MVP in 4–8 weeks.",
        "children": [
            "p3_startup_traction",
            "p3_startup_funded",
            "p3_startup_slow",
            "p3_startup_failed",
        ],
    },
    {
        "id": "p2_startup_devtools",
        "phase": 1,
        "node_type": "startup",
        "label": "🔧 Dev Tools /\\nInfrastructure",
        "salary": "220K + 0–30K\\nPKR/mo",
        "probability": 0.30,
        "color": "#e84393",
        "note": "Build tools you wish existed. CLI tools, VS Code extensions, CI/CD integrations, monitoring. Developer audience is hard but loyal. Open-source → commercial is proven path.",
        "children": ["p3_startup_traction", "p3_startup_slow", "p3_startup_failed"],
    },
    {
        "id": "p2_startup_general",
        "phase": 1,
        "node_type": "startup",
        "label": "💡 General SaaS\\n/ Micro-SaaS",
        "salary": "220K + 0–80K\\nPKR/mo",
        "probability": 0.30,
        "color": "#e84393",
        "note": "Solve a niche problem. Micro-SaaS ($1–10K MRR) is achievable solo. Examples: niche CRMs, automation tools, vertical SaaS for specific industries. Lower ceiling but faster to profitability.",
        "children": ["p3_startup_traction", "p3_startup_slow", "p3_startup_failed"],
    },
    # ─── Phase 2: Startup Outcomes ───
    {
        "id": "p3_startup_traction",
        "phase": 2,
        "node_type": "startup",
        "label": "📈 Got Traction\\n$1–5K MRR",
        "salary": "220K + 230K–1.15M\\nPKR/mo",
        "probability": 0.20,
        "color": "#e84393",
        "note": "Product-market fit signals. Growing MRR, low churn, organic signups. Key decision: keep job for safety or go full-time to accelerate. Only ~10–20% of side projects reach this.",
        "children": ["p4_startup_scale", "p4_startup_lifestyle"],
    },
    {
        "id": "p3_startup_funded",
        "phase": 2,
        "node_type": "startup",
        "label": "💰 Seed Funded /\\nAccelerator",
        "salary": "Quit job\\n$50–100K salary\\n+ equity",
        "probability": 0.08,
        "color": "#e84393",
        "note": "Got into YC, Techstars, or raised a seed round ($100K–500K). Quit job, go full-time. High risk but massive upside if it works. Rare for Pakistani founders but growing.",
        "children": ["p4_startup_scale", "p4_startup_acquired", "p4_startup_abandoned"],
    },
    {
        "id": "p3_startup_slow",
        "phase": 2,
        "node_type": "startup",
        "label": "🐌 Low Traction\\nPivoting",
        "salary": "220K + 0–50K\\nPKR/mo",
        "probability": 0.42,
        "color": "#b2bec3",
        "note": "Built product but users aren't paying or churning fast. Most common outcome. Pivot, iterate, or try a new idea. Each failed attempt teaches something. Portfolio value accumulates.",
        "children": [
            "p4_startup_lifestyle",
            "p4_startup_pivot_remote",
            "p4_startup_abandoned",
        ],
    },
    {
        "id": "p3_startup_failed",
        "phase": 2,
        "node_type": "startup",
        "label": "❌ Failed to Ship\\nor No Market Fit",
        "salary": "220K PKR/mo\\n(back to career)",
        "probability": 0.30,
        "color": "#d63031",
        "note": "Never shipped, or shipped and nobody cared. 70% of side projects never launch. Not wasted — you built skills, a portfolio, and a GitHub profile that helps with remote jobs.",
        "children": ["p4_startup_pivot_remote", "p4_startup_abandoned"],
    },
    # ─── Phase 3: Startup Final Outcomes ───
    {
        "id": "p4_startup_scale",
        "phase": 3,
        "node_type": "startup",
        "label": "🏆 Scaled to\\n$10–50K MRR\\n(quit job)",
        "salary": "2.3–11.5M PKR/mo",
        "probability": 0.10,
        "color": "#e84393",
        "note": "Unicorn indie hacker outcome. $120–600K/yr from your own product. Full autonomy, location independent. Fewer than 5% of startups reach this. But you only need to win once.",
        "children": [],
    },
    {
        "id": "p4_startup_acquired",
        "phase": 3,
        "node_type": "startup",
        "label": "🤝 Acqui-hired /\\nStartup Acquired",
        "salary": "$200–500K payout\\n+ new job",
        "probability": 0.05,
        "color": "#e84393",
        "note": "Company or team acquired. One-time payout ($200K–$500K) plus employment at acquirer. Rare but real — especially for AI startups with good tech.",
        "children": [],
    },
    {
        "id": "p4_startup_lifestyle",
        "phase": 3,
        "node_type": "startup",
        "label": "🏖 Lifestyle Biz\\n$3–10K MRR\\nSide Income",
        "salary": "Career + 700K–\\n2.3M PKR/mo",
        "probability": 0.25,
        "color": "#74b9ff",
        "note": "Best risk-adjusted startup outcome. Keep career for stability, product earns $3–10K/mo passively. Compound over multiple products. Many indie hackers live this way.",
        "children": [],
    },
    {
        "id": "p4_startup_pivot_remote",
        "phase": 3,
        "node_type": "startup",
        "label": "🌐 Startup Failed\\n→ Portfolio Helps\\nGet Remote Job",
        "salary": "1.5–2.5M PKR/mo\\n($65–110K remote)",
        "probability": 0.35,
        "color": "#00cec9",
        "note": "Startup didn't work but you built real products, shipped code, managed infra. This portfolio is gold for remote job applications. Many founders land better jobs after failing.",
        "children": [],
    },
    {
        "id": "p4_startup_abandoned",
        "phase": 3,
        "node_type": "startup",
        "label": "🚪 Abandoned\\nBack to Career",
        "salary": "Career salary only",
        "probability": 0.25,
        "color": "#636e72",
        "note": "Startup attempts fizzled out. Time spent wasn't wasted — technical skills sharpened, product thinking improved. Return to career track with broader perspective.",
        "children": [],
    },
    # ═══════════════════════════════════════════════════════════
    # FREELANCING / CONSULTING PATH
    # ═══════════════════════════════════════════════════════════
    # ─── Phase 0: Start Freelancing ───
    {
        "id": "p1_freelance",
        "phase": 0,
        "node_type": "freelance",
        "label": "💼 AI/ML\\nFreelancing\\n(Side Hustle)",
        "salary": "220K PKR/mo\\n+ project income",
        "probability": 0.18,
        "color": "#00b894",
        "note": "Start on Upwork/Toptal, build client base evenings/weekends. AI/ML freelancers command premium rates ($50–150/hr). First 3 months: build profile, take lower rates to get reviews.",
        "children": [
            "p2_freelance_platform",
            "p2_freelance_direct",
            "p2_freelance_agency",
        ],
    },
    # ─── Phase 1: Freelancing Channels ───
    {
        "id": "p2_freelance_platform",
        "phase": 1,
        "node_type": "freelance",
        "label": "🌐 Platform-Based\\nUpwork / Toptal",
        "salary": "220K + 100–300K\\nPKR/mo",
        "probability": 0.45,
        "color": "#00b894",
        "note": "Upwork for volume, Toptal for premium. AI/ML is top-paying category. $30–80/hr initially, $80–150/hr after 6 months of 5-star reviews. Platform takes 10–20% cut.",
        "children": [
            "p3_freelance_fulltime",
            "p3_freelance_side",
            "p3_freelance_dried",
        ],
    },
    {
        "id": "p2_freelance_direct",
        "phase": 1,
        "node_type": "freelance",
        "label": "🤝 Direct Clients\\nLinkedIn / Referrals",
        "salary": "220K + 150–500K\\nPKR/mo",
        "probability": 0.30,
        "color": "#00b894",
        "note": "Higher rates, no platform cut. Build through LinkedIn content, tech talks, open-source contributions. Slower to start but higher ceiling. Retainer contracts are the goal.",
        "children": [
            "p3_freelance_fulltime",
            "p3_freelance_side",
            "p3_freelance_dried",
        ],
    },
    {
        "id": "p2_freelance_agency",
        "phase": 1,
        "node_type": "freelance",
        "label": "🏢 Build AI\\nConsultancy /\\nAgency",
        "salary": "220K + 50–200K\\nPKR/mo",
        "probability": 0.25,
        "color": "#00b894",
        "note": "Hire 1–2 junior devs, take on larger projects. Higher revenue but management overhead. Agency model: you sell, juniors execute. Margins 40–60% on projects.",
        "children": [
            "p3_freelance_fulltime",
            "p3_freelance_side",
            "p3_freelance_dried",
        ],
    },
    # ─── Phase 2: Freelancing Outcomes ───
    {
        "id": "p3_freelance_fulltime",
        "phase": 2,
        "node_type": "freelance",
        "label": "🚀 Quit Job\\nFull-Time\\nFreelancer",
        "salary": "1.15–2.3M PKR/mo\\n($5–10K/mo)",
        "probability": 0.35,
        "color": "#00b894",
        "note": "Enough clients to quit job. $5–10K/mo from freelancing. Full autonomy, flexible schedule. Risk: client concentration and income variability. Keep 6-month runway saved.",
        "children": [
            "p4_freelance_premium",
            "p4_freelance_stable",
            "p4_freelance_burnout",
        ],
    },
    {
        "id": "p3_freelance_side",
        "phase": 2,
        "node_type": "freelance",
        "label": "⚖️ Keep Job +\\nSteady Freelance\\nIncome",
        "salary": "220K + 200–500K\\nPKR/mo",
        "probability": 0.40,
        "color": "#74b9ff",
        "note": "Best of both worlds. Job for stability + freelance for extra income. 10–15 hrs/week freelancing. Risk: burnout from dual workload. Sustainable for 2–3 years max.",
        "children": [
            "p4_freelance_stable",
            "p4_freelance_to_remote",
            "p4_freelance_burnout",
        ],
    },
    {
        "id": "p3_freelance_dried",
        "phase": 2,
        "node_type": "freelance",
        "label": "📉 Clients Dried\\nUp / Burnout",
        "salary": "220K PKR/mo\\n(back to job only)",
        "probability": 0.25,
        "color": "#636e72",
        "note": "Client pipeline empty, or burned out from working 60+ hr weeks (job + freelance). Common at month 6–12. Not a failure — freelance reputation still on profile for future opportunities.",
        "children": ["p4_freelance_to_remote", "p4_freelance_burnout"],
    },
    # ─── Phase 3: Freelancing Final Outcomes ───
    {
        "id": "p4_freelance_premium",
        "phase": 3,
        "node_type": "freelance",
        "label": "🏆 Premium AI\\nConsultant\\n($15–30K/mo)",
        "salary": "3.5–7M PKR/mo",
        "probability": 0.20,
        "color": "#00b894",
        "note": "Top-tier AI consultant. $150–250/hr. Clients include US/EU startups and enterprises. Selective about projects. 3–4 clients at a time. Best freelancing outcome.",
        "children": [],
    },
    {
        "id": "p4_freelance_stable",
        "phase": 3,
        "node_type": "freelance",
        "label": "💼 Stable\\nFreelancer\\n($8–12K/mo)",
        "salary": "1.85–2.8M PKR/mo",
        "probability": 0.40,
        "color": "#74b9ff",
        "note": "Reliable $8–12K/mo from 2–3 long-term clients. Good work-life balance. Equivalent to senior remote salary but with more flexibility and no boss.",
        "children": [],
    },
    {
        "id": "p4_freelance_to_remote",
        "phase": 3,
        "node_type": "freelance",
        "label": "🌐 Freelance Rep\\n→ Full-Time\\nRemote Job",
        "salary": "1.6–2.5M PKR/mo\\n($70–110K)",
        "probability": 0.25,
        "color": "#00cec9",
        "note": "Freelancing built your reputation and client network. A client offers full-time role, or your Toptal profile gets you direct employment. Common and lucrative transition.",
        "children": [],
    },
    {
        "id": "p4_freelance_burnout",
        "phase": 3,
        "node_type": "freelance",
        "label": "😩 Burnout\\nReturn to\\nEmployment",
        "salary": "Career salary\\n(possibly higher)",
        "probability": 0.15,
        "color": "#636e72",
        "note": "Freelancing is exhausting — sales, delivery, invoicing, taxes all on you. Many return to employment with better negotiating position. Freelance experience = higher offers.",
        "children": [],
    },
]


def import_career_nodes():
    """Import all career nodes into the database."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Clear existing career nodes
    cursor.execute("DELETE FROM career_nodes")
    print(f"Cleared existing career_nodes table")

    # Insert all nodes
    for node in CAREER_NODES:
        cursor.execute(
            """
            INSERT INTO career_nodes (id, phase, label, salary, probability, color, note, children, node_type)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (
                node["id"],
                node["phase"],
                node["label"],
                node.get("salary"),
                node.get("probability"),
                node.get("color"),
                node.get("note"),
                json.dumps(node.get("children", [])),
                node.get("node_type", "career"),
            ),
        )

    conn.commit()

    # Verify
    cursor.execute("SELECT COUNT(*) FROM career_nodes")
    total = cursor.fetchone()[0]

    cursor.execute(
        "SELECT node_type, COUNT(*) FROM career_nodes GROUP BY node_type ORDER BY node_type"
    )
    by_type = cursor.fetchall()

    cursor.execute(
        "SELECT phase, COUNT(*) FROM career_nodes GROUP BY phase ORDER BY phase"
    )
    by_phase = cursor.fetchall()

    conn.close()

    print(f"\n✅ Imported {total} career nodes into {DB_PATH}")
    print(f"\nBy type:")
    for node_type, count in by_type:
        print(f"  {node_type}: {count}")
    print(f"\nBy phase:")
    for phase, count in by_phase:
        print(f"  Phase {phase}: {count}")


if __name__ == "__main__":
    import_career_nodes()
